### ISSUE TITLE
Count cannot be less than zero. (Parameter 'repeatCount')

### ISSUE THREAD

**Issue by kheldorn** [DvdKhl/AVDump3#39]
https://anidb.net/admin/avmf/error/?do=xml&id=723949
https://anidb.net/admin/avmf/error/?do=xml&id=723948
https://anidb.net/admin/avmf/error/?do=xml&id=723786

`<Commandline>O:\Profile\AVDump3\AVDump3CL.dll FROMFILE O:\Profile\AVDump3\arguments.txt .</Commandline>`

Possibly an issue with "." given as the path? "--PrintDiscoveredFiles" doesn't show anything weird though. https://i.imgur.com/1Uaf4nt.png (ignore the "System.NullReferenceException")

**Comment by DvdKhl** [comment]
Fixed that specific exception, I have no clue what the root cause is though.
