### ISSUE TITLE
"Error System.InvalidOperationException: MediaInfoLib couldn't open the file" because of "weird" UTF-8 character in filename

### ISSUE THREAD

**Issue by kheldorn** [DvdKhl/AVDump3#49]
Trying to dump e.g. "`(Hi10)_Space☆Dandy_-_01_(720p)_(Commie)_(Dual_Audio)_(F042204B).mkv`" will throw an "Error System.InvalidOperationException: MediaInfoLib couldn't open the file" exception.

Remove the "☆" and dumping will work.

Should MIL even be called at all on such a file? It is an .mkv file afterall and shouldn't require MIL?

**Comment by DvdKhl** [comment]
I haven't been able to reproduce it on Win10 or Debian.

**Comment by DvdKhl** [comment]
```
18 12 43 <@Arokh> f00b4r, could you try "export LANG=C.UTF-8; export LC_ALL=C.UTF-8" before running AVD3?
18 13 32 <f00b4r> moments
18 17 23 <&worf> no idea. cant break it on win10 no matter what random star symbol i use
18 19 51 <f00b4r> Arokh: that worked
18 20 13 <f00b4r> the locale was fr_FR.UTF-8 before that
```
