### ISSUE TITLE
Wrong ed2k links are generated from symlinks on linux

### ISSUE THREAD

**Issue by Hark0nnen** [DvdKhl/AVDump3#51]
the generated ed2k links look like this f.e
ed2k://|file|Irozuku Sekai no Ashita kara - 01 (BD 1080p) [F7505C7B].mkv|130|E69431115E758BD3EB0F8B878D1F370A|/

notice 130 instead of actual file size of what symlink points too

**Comment by DvdKhl** [comment]
Fixed in the next version.
