### ISSUE TITLE
'IOException: Cannot access file' when conccurently proccessing files 

### ISSUE THREAD

**Issue by GrumpyBear57** [DvdKhl/AVDump3#53]
AVD Version: 8188 (From AniDB wiki download link)
Command: `.\AVDump3CL.exe --Concurrent=4 --Ed2kLogPath={snip path}\ed2k.txt {snipped other args} {snipped path to files}`
Exception: `Error System.IO.IOException: The process cannot access the file '{snip path}\ed2k.txt' because it is being used by another process.`

This would probably be hard to reproduce intentionally, so I can't be 100% sure what caused it. My suspicion is, when processing multiple files concurrently, if two or more files finish at the same time, the ed2k hash file writer is called without any safety to ensure that the file isn't already open. I can also see that I'm missing two ed2k hashes from the file from either when or after the exception was thrown (don't know what file it threw on).

**Comment by DvdKhl** [comment]
The filepath you specified for the ed2k output is contained in the path for the files to be processed.
Now AVD3 will at some point try to process "{snip path}\ed2k.txt" which it can't because it is locked.

Either move that file outside the processing folder or tell AVD3 not to process txt files (--WExt=-txt)

**Comment by GrumpyBear57** [comment]
Yeah I figured that out when I processed only one file and ended up with a ed2k.txt hash in ed2k.txt, so I've got it moved out now. Would be nice if this exception was caught though, so it doesn't bail immediately from processing the rest of the files. That way when you get that odd idiot (like me) who happens to put the output file in the input directory, it doesn't blow up.

**Comment by DvdKhl** [comment]
Not sure if I'll add exceptions but it shouldn't completely crash either.
I'll at least catch the exception so it doesn't crash.

**Comment by GrumpyBear57** [comment]
Sounds good, thanks!
